/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@protocol ScreenSaverControl
- (BOOL)screenSaverIsRunning;
- (BOOL)screenSaverCanRun;
- (void)setScreenSaverCanRun:(BOOL)fp8;
- (void)screenSaverStartNow;
- (void)screenSaverStopNow;
- (void)restartForUser:(id)fp8;
- (double)screenSaverTimeRemaining;
- (void)screenSaverDidFade;
- (BOOL)screenSaverIsRunningInBackground;
- (void)screenSaverDidFadeInBackground:(BOOL)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;
@end

@interface ScreenSaverController : NSObject <ScreenSaverControl>
{
    NSConnection *_connection;
    id _daemonProxy;
    void *_reserved;
}

+ (id)controller;
+ (id)monitor;
+ (id)daemonConnectionName;
+ (id)enginePath;
- (void)_connectionClosed:(id)fp8;
- (id)init;
- (void)dealloc;
- (BOOL)screenSaverIsRunning;
- (BOOL)screenSaverCanRun;
- (void)setScreenSaverCanRun:(BOOL)fp8;
- (void)screenSaverStartNow;
- (void)screenSaverStopNow;
- (void)restartForUser:(id)fp8;
- (double)screenSaverTimeRemaining;
- (void)screenSaverDidFade;
- (BOOL)screenSaverIsRunningInBackground;
- (void)screenSaverDidFadeInBackground:(BOOL)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;

@end

@interface ScreenSaverEngine : NSResponder
{
    NSMutableArray *_windows;
    NSString *_moduleName;
    BOOL _debug;
    BOOL _debugLogging;
    BOOL _background;
    BOOL _mainOnly;
    BOOL _isRunning;
    BOOL _runFromPref;
    BOOL _blackSaver;
    BOOL _lockCountdown;
    int _retCode;
    struct _NSRect _mouseAllowedRect;
    struct _NSPoint _startingMousePoint;
    BOOL _keyEventTerminated;
    float _screenLockDelay;
    BOOL _performGammaFade;
    struct {
        struct CGRect thing1;
        int thing2;
    } *_cornerList;
    int _cornerListCnt;
    id _delegate;
}

- (id)init;
- (void)dealloc;
- (void)applicationDidFinishLaunching:(id)fp8;
- (int)_stateForMousePosition:(struct CGPoint)fp8 mask:(unsigned int)fp16;
- (void)_setupCornerShapes;
- (id)_makeWindowForSaver:(id)fp8 frame:(struct _NSRect)fp12 backingStoreType:(unsigned int)fp28;
- (void)_cancelKey:(id)fp8;
- (void)_resetTrackingRects;
- (void)_timedHideCursor;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidResignActive:(id)fp8;
- (void)startScreenSaver:(BOOL)fp8;
- (void)stopScreenSaver:(id)fp8;
- (void)pauseScreenSaver;
- (void)unpauseScreenSaver;
- (void)readjustDisplays;
- (BOOL)isBackground;
- (int)retCode;
- (void)setRunFromPref:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (BOOL)isRunning;
- (void)keyDown:(id)fp8;
- (void)flagsChanged:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (void)rightMouseUp:(id)fp8;
- (void)scrollWheel:(id)fp8;
- (void)tabletPoint:(id)fp8;

@end
